<?php
/**
 * Cminds MultiUserAccounts frontend subaccount edit template.
 *
 * @category Cminds
 * @package  Cminds_MultiUserAccounts
 * @author   Piotr Pierzak <piotr@cminds.com>
 */
?>
<?php
/** @var \Cminds\MultiUserAccounts\Block\Manage\Form\Edit $block */
?>
<?php $canManageSub = $block->getCanManageSubaccounts(); ?>
<form class="form form-edit-account"
      action="<?php echo $block->escapeUrl($block->getFormActionUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      autocomplete="off"
	  data-mage-init='{"validation":{}}'
	  >
    <?php
    if($block->getSubaccount()->getCustomerId()){
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $customerFactory = $objectManager->get('\Magento\Customer\Model\CustomerFactory')->create();
        $customerId = $block->getSubaccount()->getCustomerId();
        $customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
        $customer = $customerRepository->getById($customerId);
        $FirstName = $customer->getFirstname();
        $LastName = $customer->getFirstname();
        if($customer->getCustomAttribute('pg_phonenumber') != '')
        {
          $PgPhonenumber = $customer->getCustomAttribute('pg_phonenumber')->getValue();
        }
        else
        {
          $PgPhonenumber = ''; 
        } 
    }
    else
    {
        $FirstName = '';
        $LastName = '';
        $PgPhonenumber = '';         
    }
    ?>
    <fieldset class="fieldset info">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Subaccount Information') ?></span>
        </legend><br>
        <?php if ($block->getSubaccount()->getId()) : ?>
            <input type="hidden"
                   name="id"
                   value="<?php echo $block->escapeHtml($block->getSubaccount()->getId()) ?>"/>
        <?php endif; ?>

        <?php // $block->getNameWidgetHtml() ?>
	 
		<div class="field field-name-firstname required">
            <label class="label" for="<?php echo __('firstname'); ?>">
                <span><?php echo __('First Name'); ?></span>
            </label>

            <div class="control">
                <input type="text" maxlength="100" id="<?= $block->escapeHtml($block->getFieldId('firstname')) ?>"
                       name="<?php echo __('firstname'); ?>"
                       value="<?php echo $FirstName; ?>"
                       title="<?php echo __('First Name'); ?>"
                       class="input-text <?php echo __('firstname'); ?>" data-validate="{required:true}">
            </div>
        </div>
		
		<div class="field field-name-lastname required">
            <label class="label" for="<?php echo __('lastname'); ?>">
                <span><?php echo __('Last Name'); ?></span>
            </label>

            <div class="control">
                <input type="text" maxlength="100" id="<?= $block->escapeHtml($block->getFieldId('lastname')) ?>"
                       name="<?php echo __('lastname'); ?>"
                       value="<?php echo $LastName; ?>"
                       title="<?php echo __('Last Name'); ?>"
                       class="input-text <?php echo __('lastname'); ?>" data-validate="{required:true}">
            </div>
        </div>        
        <div class="field field-name-email required">
            <label class="label"
                   for="email">
                <span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
            </label>
            <div class="control">
                <input type="email"
                       id="email"
                       name="email"
                       title="<?php /* @escapeNotVerified */ echo __('Email') ?>"
                       class="input-text"
                       data-validate="{required:true, 'validate-email':true}"
                       value="<?php echo $block->escapeHtml($block->getSubaccount()->getEmail()) ?>"
                    <?php if ($canManageSub) {echo '';} else {echo 'disabled';} ?>/>
            </div>
        </div>        

        <div class="field choice field-name-is-active required">
            <?php $customerId = $block->getSubaccount()->getCustomerId(); $isActive = null;?>
            <?php if ($customerId !== null) {$isActive = $block->getIsActive($customerId); }?>
            <?php if ($isActive === null) {$isActive = 1; }?>
            <input type="checkbox"
                   name="is_active"
                   id="is-active"
                   value="1"
                   title="<?php /* @escapeNotVerified */ echo __('Is Active') ?>"
                   class="checkbox" <?php if ($isActive): ?>checked="checked"<?php endif; ?>/>
            <label class="label"
                   for="is-active">
                <span><?php /* @escapeNotVerified */ echo __('Is Active') ?></span>
            </label>
        </div>
    </fieldset>

    <fieldset class="fieldset access">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Password') ?></span>
        </legend><br>

        <div class="field password required">
            <label class="label"
                   for="password">
                <span><?php /* @escapeNotVerified */ echo __('Password') ?></span>
            </label>
            <div class="control">
                <input type="password"
                       class="input-text"
                       name="password"
                       id="password"
                       autocomplete="off"
					   title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
					   data-password-min-length="6"
                       data-password-min-character-sets="1"
					   data-validate="{required:true, 'validate-customer-password':true}"
                    <?php if ($canManageSub) {echo '';} else {echo 'disabled';} ?>/>
            </div>
        </div>
        <div class="field confirm password required">
            <label class="label"
                   for="password-confirmation">
                <span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span>
            </label>
            <div class="control">
                <input type="password"
                       class="input-text"
                       name="password_confirmation"
                       id="password-confirmation"
					   title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>"
                       autocomplete="off"
					   data-validate="{required:true, equalTo:'#password'}"
                    <?php if ($canManageSub) {echo '';} else {echo 'disabled';} ?>/>
            </div>
        </div>
        <div class="field field-name-phonenumber">
            <label class="label"
                   for="pg_phonenumber">
                <span><?php /* @escapeNotVerified */ echo __('Accounts Phone') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="pg_phonenumber"
                       name="pg_phonenumber"
                       title="<?php /* @escapeNotVerified */ echo __('Accounts Phone') ?>"
                       class="input-text"
                       value="<?php echo $PgPhonenumber; ?>"
                    />
            </div>
        </div>

        <?php
        $showTaxVat = $block->showTaxVatConfiguration();
        $isForced = (bool) $block->getSubaccount()->getForceUsageParentVatPermission();
        ?>
        <?php if (!empty($showTaxVat)) : ?>
            <div class="field taxvat taxvat-hidden <?php if ($showTaxVat === 'req') echo 'required'; ?><?php if($isForced) echo ' hidden'; ?>">
                <label class="label"
                       for="taxvat">
                    <span><?php /* @escapeNotVerified */ echo __('Tax/VAT Number') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           value="<?php /* @escapeNotVerified */ echo $block->getSubaccount()->getTaxvat(); ?>"
                           class="input-text"
                           name="taxvat"
                           id="taxvat"/>
                </div>
            </div>
        <?php endif; ?>

        <?php /*
        $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <div class = 'taxvat-hidden<?php if($isForced) echo " hidden"; ?>'>
            <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
            </div>
        <?php endif; */ ?>

        <?php
        // Date of birth
        $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ( $_dob->isEnabled() ): ?>
            <?= $_dob->setDate( $block->getSubaccount()->getDob() )->toHtml() ?>
        <?php endif ?>

        <?php
        // gender
        $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender( $block->getSubaccount()->getGender() )->toHtml() ?>
        <?php endif ?>

    </fieldset>

    <fieldset class="fieldset permissions">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Permissions') ?></span>
        </legend><br>

        <?php $permissions = $block->getPermissions(); ?>
        <?php foreach ($permissions as $permissionCode => $permissionData) : ?>
            <?php 
            // skip permission display if global setting disabled
            if( false === $this->getParentCanSeeSubaccountsOrderHistory() 
                && 'account_order_history_view_permission' === $permissionCode
            ) continue; 
            ?>
            <?php $isForced = $block->isPermissionForced($permissionCode); ?>
            <div class="field choice <?php echo $block->getPermissionHtmlId($permissionCode) ?>">
                <?php $permission = $block->getSubaccount()->{$block->getPermissionGetter($permissionCode)}(); ?>
                <input type="checkbox"
                       name="<?php echo $permissionCode ?>"
                       id="<?php echo $block->getPermissionHtmlId($permissionCode) ?>"
                       value="1"
                    <?= empty($permissionData['disabled']) && !$isForced ? '' : 'disabled="disabled"' ?>
                       title="<?php /* @escapeNotVerified */ echo $permissionData['description'] ?>"
                       class="checkbox" <?php if ($permission || $isForced): ?>checked="checked"<?php endif; ?>/>
                <label class="label" for="<?php echo $block->getPermissionHtmlId($permissionCode) ?>">
                    <span><?php /* @escapeNotVerified */ echo $permissionData['description'] ?></span>
                </label>
            </div>
        <?php endforeach; ?>
    </fieldset>
    <script type="text/x-magento-init">
        {
            "#checkout-order-approval-permission": {
                "Cminds_MultiUserAccounts/js/input_dependency": {}
            }
        }
    </script>

    <fieldset class="fieldset additional-configuration">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Additional Configuration') ?></span>
        </legend><br>

        <div class="field field-name-manage-order-max-amount hidden">
            <label class="label"
                   for="manage_order_max_amount">
                <span><?php /* @escapeNotVerified */ echo __('Order Amount Without Approval') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="manage_order_max_amount"
                       name="additional_information[manage_order_max_amount]"
                       title="<?php /* @escapeNotVerified */ echo __('Order Amount Without Approval') ?>"
                       class="input-text required-entry"
                       data-validate="{required:false}"
                       value="<?php echo $block->escapeHtml($block->getSubaccount()->getAdditionalInformationValue('manage_order_max_amount')) ?>"/>
            </div>
            <div class="comment">
                <?php
                echo __(
                    'No value or 0 is equal to no limit. "Can Create Order" '
                    . 'permission has to be set.'
                );
                ?>
            </div>
        </div>

        <div class="field field-name-manage-order-approval-permission-amount">
            <label class="label"
                   for="manage_order_approval_permission_amount">
                <span><?php /* @escapeNotVerified */ echo __('Order Approval Permission Amount') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="manage_order_approval_permission_amount"
                       name="additional_information[manage_order_approval_permission_amount]"
                       title="<?php /* @escapeNotVerified */ echo __('Order Approval Permission Amount') ?>"
                       class="input-text required-entry"
                       data-validate="{required:false}"
                       value="<?php echo $block->escapeHtml($block->getSubaccount()->getAdditionalInformationValue('manage_order_approval_permission_amount')) ?>"/>
            </div>
            <div class="comment">
                <?php
                echo __(
                    'Sub-account will be allowed to approve orders with amount '
                    . 'not bigger than above amount. No value or 0 is equal to '
                    . 'no limit. "Can Approve Orders" permission has to be set.'
                );
                ?>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    title="<?php /* @escapeNotVerified */ echo __('Save') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?php /* @escapeNotVerified */ echo __('Go back') ?></span>
            </a>
        </div>
    </div>
</form>