<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if($_code == 'pg_featured_description') {?>
	<?php if ($_attributeValue): ?>
	<div class="product attribute <?= /* @escapeNotVerified */ $_className ?> <?php if(!$_product->getGuaranteeIcon()) { echo 'guarantee_icon_nofound'; } ?>">
	    <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>>
	    	<?php
	    	$short_description = substr($_attributeValue , 0, 450);
	    	echo $short_description;
	    	?>
	    </div>
	    <?php if($_product->getGuaranteeIcon()) { ?>
		    <div class="guarantee">
		    	<img src="<?php echo $this->getUrl('pub/media').'match_price.png'; ?>" alt="Guarantee" />
		    </div>
		<?php } ?>
	</div>
	<?php endif; ?>
<?php } else { ?>
	<?php if ($_attributeValue): ?>
	<div class="product attribute <?= /* @escapeNotVerified */ $_className ?>">
	    <?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */ $_attributeLabel ?></strong><?php endif; ?>
	    <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>><?= /* @escapeNotVerified */ $_attributeValue ?></div>
	</div>
	<?php endif; ?>
<?php }	 ?>
