<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
<?php $resource = $block->getProduct()->getData('pg_resources');
	  $specification = $block->getProduct()->getData('description');
?>
<?php if($resource!='' || $specification !=''){ ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $k=1; foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content" <?php if($k!=1){ echo 'style="display:none;"'; }  ?> >
					<div class="prod_detail_tab_content">
                    <?= /* @escapeNotVerified */ $html ?>
					</div>	
                </div>
            <?php $k++; endforeach;?>
        </div>
    </div>
<?php } ?>
<?php endif; ?>

<?php 
		$warehouse_helper = $this->helper('Digital\Warehouse\Helper\Data');
	  	$customerSession = $warehouse_helper->getCustomerSession();
	  	$selected_location = $customerSession->getLocationSession();
?>
<script type="text/javascript">
	require([
			'jquery',
		], function ($) {
			$(document).ready(function () {
				
				var selected_location = '<?php echo $selected_location; ?>';
				if(selected_location=='')
				{
					jQuery('#top_warehouse_popup_content').addClass('active');
					jQuery('html').addClass('show_location_popup');
					jQuery('.close-warehouse-popup').hide();
				}
				
				});
	});
</script>	
