
<div id="product_enq_loader" class="prod-enquiry-loader"><span></span></div>
<?php $enquiryQuoteProducts = $block->getEnquiryQuoteProducts();
		$helper = $this->helper('Digital\Contactus\Helper\Data');
		$key = $helper->Sitekey();

?>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('productenquiry/index/save') ?>"
          method="post"
          id="productenquiry-form"
	  	  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
		  data-mage-init='{"validation":{}}'
          class="form productenquiry-cart">
    <?= $block->getBlockHtml('formkey') ?>

	<?php if($block->isExistEnquiryQuote()): ?>
    	<div class="cart table-wrapper">
        <table id="shopping-cart-table"
               class="cart items data table">
            <caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */ __('Enquiry Items') ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= /* @escapeNotVerified */ __('Item') ?></span></th>
                    <th class="col qty" scope="col"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= /* @escapeNotVerified */ __('Remove') ?></span></th>
                </tr>
            </thead>
            <tbody>
				<?php if(count($enquiryQuoteProducts)): ?>
				<?php foreach($enquiryQuoteProducts as $product) : ?>
				<?php 
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$product_load = $objectManager->create('Magento\Catalog\Model\Product')->load($product['product_id']);
				
				?>
					<tr>
						<td data-th="Product" class="col Product">
							<div class="product-item-details">
								<strong class="product-item-name">
										<a href="<?=  /* @escapeNotVerified */ __($product['parenturl']); ?>">
											<?=  /* @escapeNotVerified */ __($product['name']); ?>
										</a>
										
								</strong>
								<div class="product_enq_code"><label><?= /* @escapeNotVerified */ __('Code:') ?></label><span><?=  /* @escapeNotVerified */ __($product_load['sku']); ?></span></div>
							</div>
						</td>
						<td class="col qty" data-th="Qty">
							<div class="field qty qty-box">
								<?=  /* @escapeNotVerified */ __($product['qty']); ?>
								<span class="increases" data-enquiryid="<?=  /* @escapeNotVerified */ __($product['product_id'].$product['parentid']); ?>">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                         width="13px" height="13px" viewBox="0 0 13 13" enable-background="new 0 0 13 13" xml:space="preserve">
                                    <path fill="#010101" d="M11.862,5.341H7.908c-0.129,0-0.232-0.104-0.232-0.232V1.155c0-0.643-0.521-1.163-1.164-1.163
                                        S5.349,0.512,5.349,1.155v3.954c0,0.129-0.104,0.232-0.232,0.232H1.163C0.52,5.341,0,5.862,0,6.504S0.52,7.668,1.163,7.668h3.954
                                        c0.129,0,0.232,0.104,0.232,0.232v3.954c0,0.643,0.521,1.163,1.163,1.163s1.164-0.521,1.164-1.163V7.9
                                        c0-0.129,0.104-0.232,0.232-0.232h3.954c0.643,0,1.163-0.521,1.163-1.164S12.505,5.341,11.862,5.341z"/>
                                    </svg>    
                                </span>
								<span class="decreases" data-enquiryid="<?=  /* @escapeNotVerified */ __($product['product_id'].$product['parentid']); ?>">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                         width="13px" height="13px" viewBox="0 0 13 13" enable-background="new 0 0 13 13" xml:space="preserve">
                                    <g>
                                        <g>
                                            <path fill="#010101" d="M12.295,5.593H6.349H0.706C0.483,5.593,0,5.896,0,6.5s0.483,0.907,0.706,0.907h5.643h5.946
                                                C12.518,7.407,13,7.104,13,6.5S12.518,5.593,12.295,5.593z"/>
                                        </g>
                                    </g>
                                    </svg>
                                </span>
							</div>
						</td>
						<td class="col action" colspan="100">
							<a href="javascript:void(0)" title="Remove item" class="actiondelete button-gray" data-enquiryid="<?=  /* @escapeNotVerified */ __($product['product_id'].$product['parentid']); ?>">
								<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="18px" height="18px" viewBox="0 0 18 18" enable-background="new 0 0 18 18" xml:space="preserve">
                                    <g>
                                        <path fill="#FFFFFF" d="M8.939,0C4.01,0,0,4.018,0,8.956c0,4.938,4.01,8.956,8.939,8.956c4.928,0,8.939-4.019,8.939-8.956
                                            C17.878,4.018,13.867,0,8.939,0z M8.939,16.377c-4.084,0-7.407-3.33-7.407-7.421c0-4.092,3.322-7.421,7.407-7.421
                                            c4.083,0,7.406,3.329,7.406,7.421C16.345,13.047,13.022,16.377,8.939,16.377z"></path>
                                        <path fill="#FFFFFF" d="M12.398,5.491c-0.301-0.3-0.785-0.3-1.084,0l-2.375,2.38l-2.375-2.38c-0.299-0.3-0.784-0.3-1.083,0
                                            c-0.299,0.299-0.299,0.786,0,1.085l2.375,2.38l-2.375,2.38c-0.299,0.3-0.299,0.785,0,1.086c0.15,0.15,0.347,0.225,0.542,0.225
                                            c0.196,0,0.393-0.074,0.542-0.225l2.375-2.381l2.375,2.381c0.149,0.15,0.346,0.225,0.542,0.225c0.195,0,0.392-0.074,0.542-0.225
                                            c0.298-0.301,0.298-0.786,0-1.086l-2.376-2.38l2.376-2.38C12.696,6.277,12.696,5.791,12.398,5.491z"></path>
                                    </g>
                                    </svg>
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
				<?php endif; ?>
			</tbody>
        </table>
      </div>
	<?php endif; ?>
	<?php if($block->isExistEnquiryQuote()): ?>
	<fieldset class="fieldset">
        <div class="form-wrapper">
            <div class="form-left">
                 <div class="field required">
                        <div class="control">
                            <label class="label" for="fullname"><span><?php /* @escapeNotVerified */ echo __('Full Name') ?><sup>*</sup></span></label>
                            <input type="text" name="fullname" value="<?= $block->getFullname(); ?>" title="<?= $block->escapeHtmlAttr(__('Full Name')) ?>" class="input-text" id="fullname" data-validate="{required:true}" maxlength="100">
                        </div>
                 </div>
                <div class="field required">
                    <div class="control">
                        <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?><sup>*</sup></span></label>
                        <input type="email" name="email" id="email" value="<?= $block->getEmailaddress(); ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" maxlength="100">
                    </div>
                </div>
                <div class="field required">
                          <div class="control">
                              <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                            <input type="text" name="company" value="<?= $block->getNscompanyname(); ?>" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" class="input-text" id="company" maxlength="250">
                        </div>
                 </div>
            </div>
            <div class="form-right">
                <div class="field required">
                    <div class="control">
                        <label class="label" for="phone"><span><?php /* @escapeNotVerified */ echo __('Phone') ?><sup>*</sup></span></label>
                        <input type="text" name="phone" id="phone" value="" title="<?= $block->escapeHtmlAttr(__('Phone')) ?>" class="input-text" data-validate="{required:true}" maxlength="20">
                    </div>
                </div>
                <div class="field required comment">
                    <div class="control">
                        <label class="label" for="phone"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></label>
                        <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('comment')) ?>" class="input-text"></textarea>
                    </div>
                </div>
            </div>
			
			<div class="field captcha">
                        <div class="gcaptcha_wrap">
                          <div class="g-recaptcha" data-sitekey="<?php echo $key; ?>"></div>
                          <div class="recaptcha-error-message validation-advice" style="display:none;" >
                            <?php /* @escapeNotVerified */ echo __('Please verify that you are not a robot.') ?>
                          </div>
                        </div>
                      </div>
			
            <div class="form-footer">
            <div class="field required submit">
                <div class="actions-toolbar">
                    <div class="primary">

                        <button onclick="window.location.href='<?php echo $this->getBaseUrl(); ?>'; return false;" type="button"  class="action submit btn-grey" title="<?= $block->escapeHtmlAttr(__('Add More Products')) ?>"><span><?= $block->escapeHtml(__('Add More Products')) ?></span></button>

                        <button type="submit" class="action submit btn-green submit_product_enquiry" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
                    </div>
                </div>		
		</div>
            </div>
        </div>
	</fieldset>
		
	<?php else: ?>
	    <div class="noproductenquiry">
			<p><?= $block->escapeHtml(__('You have no items in your product enquiry list.')) ?></p>			
    		<p><?php echo __('Click'); ?> <a href="<?php echo $this->getBaseUrl().'products.html'; ?>"><?php echo __('here'); ?></a><?php echo __(' to continue browsing.'); ?></p>
		</div>
	<?php endif; ?>
</form>

<?php /* enquiry js code start from here */ ?>

<script type="text/javascript">
	  require([ 'jquery','domReady!'],function($){
		  
		  
		  jQuery("#productenquiry-form").submit(function(event) {
				var response = grecaptcha.getResponse();
				if (response.length == 0) {
					jQuery('.recaptcha-error-message').show();
					return false;
				} else {
					jQuery('.recaptcha-error-message').hide();
					
				}
			});
		  
		  var onSuccess = function(response) {
				var errorDivs = document.getElementsByClassName("recaptcha-error");
				if (errorDivs.length) {
					errorDivs[0].className = "";
				}
				var errorMsgs = document.getElementsByClassName("recaptcha-error-message");
				if (errorMsgs.length) {
					errorMsgs[0].parentNode.removeChild(errorMsgs[0]);
				}
			};
		  
		  
		  jQuery(document).delegate('form', 'submit', function(event) {
		    var form = jQuery(this);
		    var formId = form.attr('id');				   
			if(jQuery(form).valid()){
				window.submitButtonHtml = jQuery('#'+formId).find( "button[type=submit]" ).html();
				window.submitButton = jQuery('#'+formId).find( "button[type=submit]" );
				window.submitButton.html('<span>Please wait...</span>');
				window.submitButton.attr("disabled", "disabled");
				setTimeout(function(){ 
					window.submitButton.html(submitButtonHtml);
					window.submitButton.removeAttr("disabled");
				}, 10000);
			}
	    }); 
		  
		  
		  $('.actiondelete').click(function(){
			  	var Products = [];
				var enquiryid  = $(this).data('enquiryid');
				if(enquiryid > 0)
				{
					   Products.push(enquiryid);
				}
				if(Products.length)
				{
					var productenquiryUrl = "<?php echo $this->getUrl().'productenquiry/index/deletes'?>";
					var data = 'products='+ Products;
				  	jQuery.ajax({
						url: productenquiryUrl,
						type: "POST",        
						data: data,     
						cache: false,
						dataType: 'json',
						success: function (urldata) {
							 if( urldata != "error" )
							 {
								window.location = urldata;
							 } 
						},
						error: function (jqXHR, textStatus, errorThrown) {
							 alert(textStatus);
						}
					});
			    } 
		  });
		  
		   $('.increases').click(function(){
			   jQuery('#product_enq_loader').show();
			  	var Products = [];
				var enquiryid  = $(this).data('enquiryid');
				if(enquiryid > 0)
				{
					   Products.push(enquiryid);
				}
				if(Products.length)
				{
					var productenquiryUrl = "<?php echo $this->getUrl().'productenquiry/index/increases'?>";
					var data = 'products='+ Products;
				  	jQuery.ajax({
						url: productenquiryUrl,
						type: "POST",        
						data: data,     
						cache: false,
						dataType: 'json',
						success: function (urldata) {
							 if( urldata != "error" )
							 {
								window.location = urldata;
							 } 
						},
						error: function (jqXHR, textStatus, errorThrown) {
							 alert(textStatus);
						}
					});
			    } 
		  });
		  
		  $('.decreases').click(function(){
			  jQuery('#product_enq_loader').show();
			  	var Products = [];
				var enquiryid  = $(this).data('enquiryid');
				if(enquiryid > 0)
				{
					   Products.push(enquiryid);
				}
				if(Products.length)
				{
					var productenquiryUrl = "<?php echo $this->getUrl().'productenquiry/index/decreases'?>";
					var data = 'products='+ Products;
				  	jQuery.ajax({
						url: productenquiryUrl,
						type: "POST",        
						data: data,     
						cache: false,
						dataType: 'json',
						success: function (urldata) {
							 if( urldata != "error" )
							 {
								window.location = urldata;
							 } 
						},
						error: function (jqXHR, textStatus, errorThrown) {
							 alert(textStatus);
						}
					});
			    } 
		  });
	  }); 
</script>
<?php /* enquiry js code end here */ ?>

