<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items roduct ">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item ">' : '</li><li class="item product product-item">' ?>
                <div class="pro-inner">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                        <div class="product-item-img">
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                        </div>
                    <div class="product details product-item-details product-info">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name product-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>

						<div class="btn-prod-cart">
						      <a class="product-item-link" title="<?=  __('Add to Cart') ?>" href="<?= $_product->getProductUrl() ?>">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="24px" height="19.381px" viewBox="0 0 24 19.381" enable-background="new 0 0 24 19.381" xml:space="preserve">
                                <g>
                                    <path fill="#FFFFFF" d="M21.029,12.655l2.828-8.464c0.142-0.407,0.035-0.652-0.08-0.813c-0.293-0.413-0.896-0.417-1.012-0.417
                                        L6.78,2.957L6.353,0.933C6.237,0.456,5.897,0,5.211,0H0.719C0.253,0,0,0.218,0,0.654v1.168c0,0.421,0.253,0.531,0.735,0.531h3.793
                                        l2.903,12.323c-0.461,0.49-0.712,1.2-0.712,1.866c0,1.461,1.164,2.809,2.65,2.809c1.403,0,2.456-1.315,2.627-2.099h5.653
                                        c0.172,0.783,1.024,2.129,2.627,2.129c1.461,0,2.649-1.266,2.649-2.724c0-1.453-0.884-2.738-2.634-2.738
                                        c-0.73,0-1.593,0.394-1.995,0.979h-6.946c-0.504-0.781-1.193-1.025-1.889-1.054l-0.097-0.515h10.571
                                        C20.73,13.329,20.887,13.041,21.029,12.655z M20.296,15.628c0.551,0,0.996,0.447,0.996,0.996s-0.445,0.995-0.996,0.995
                                        s-0.997-0.443-0.997-0.995C19.3,16.075,19.745,15.628,20.296,15.628z M10.354,16.624c0,0.558-0.452,1.01-1.006,1.01
                                        c-0.556-0.003-1.008-0.452-1.008-1.01c0-0.555,0.452-1.007,1.008-1.007C9.903,15.617,10.354,16.069,10.354,16.624z"/>
                                </g>
                                </svg>
								  <?php if($viewMode=='list'){ ?><span class="list-add-to-cart-icon"><?=  __('Add to Cart') ?></span> <?php } ?>
                                </a>
						</div>

						<?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?=  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?=  $_product->getProductUrl() ?>" title="<?=  $_productNameStripped ?>"
                                       class="action more"><?=  __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>

						<?php /* $block->getReviewsSummaryHtml($_product, $templateType) */ ?>

                        <?php /* $block->getProductDetailsHtml($_product) */ ?>

                        <?php /*<div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?=  $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?=  $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?=  Action::PARAM_NAME_URL_ENCODED ?>" value="<?=  $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?=  __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?=  __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?=  __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?=  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?=  $_product->getProductUrl() ?>" title="<?=  $_productNameStripped ?>"
                                       class="action more"><?=  __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div> */ ?>




                    </div>
                </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="bottom-toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
