<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl();
?>
<div class="block block-customer-login" id="login-popup-modal-fly" style="display:none;">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form-popup"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
				<div class="login-popup-error-msg message-error error message" id="popup_login_error_msg" style="display:none;"></div>

                <div class="field email required">
                    <label class="label" for="emailnew"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input maxlength="75" name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" autocomplete="off" id="emailnew" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="passwordnew" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input maxlength="25" name="login[password]" type="password" autocomplete="off" class="input-text" id="passwordnew" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="secondary forgot_pass"><a class="action remind" href="<?php echo $url."customer/account/forgotpassword"; ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="submit-button"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="register-box">
                        <div class="info-text-box">
                            <div class="info-text-left">
                                <span class="icon">
                                    <svg x="0px" y="0px" width="22px" height="23.204px" viewBox="0 0 22 23.204" enable-background="new 0 0 22 23.204">
                                        <g>
                                            <g>
                                                <path fill="#64BD61" d="M12.349,20.324c-0.174,0.245-0.427,0.424-0.718,0.504l-1.443,0.394c-0.113,0.032-0.23,0.049-0.348,0.049
                                                    c-0.267,0-0.524-0.081-0.74-0.233c-0.318-0.222-0.518-0.57-0.55-0.949l-0.126-1.489c-0.03-0.308,0.052-0.613,0.226-0.859
                                                    l0.054-0.076H3.554c-0.416,0-0.752-0.343-0.752-0.758s0.337-0.758,0.752-0.758h6.231l1.393-1.989H3.554
                                                    c-0.416,0-0.752-0.343-0.752-0.758c0-0.416,0.337-0.758,0.752-0.758l8.698-0.021l3.261-4.677V4.481
                                                    c0-0.57-0.441-1.028-1.009-1.028h-2.496v1.976c0,0.933-0.763,1.67-1.693,1.67H5.293c-0.934,0-1.669-0.738-1.669-1.67V3.453H1.1
                                                    c-0.568,0-1.029,0.459-1.029,1.028V22.15c0,0.568,0.461,1.054,1.029,1.054h13.403c0.569,0,1.009-0.485,1.009-1.054v-6.318
                                                    L12.349,20.324z M3.554,9.137h8.497c0.414,0,0.751,0.342,0.751,0.757c0,0.415-0.337,0.757-0.751,0.757H3.554
                                                    c-0.416,0-0.752-0.342-0.752-0.757C2.802,9.479,3.139,9.137,3.554,9.137z"/>
                                                <path fill="#64BD61" d="M5.307,6.105h5.017c0.38,0,0.689-0.309,0.689-0.689V2.531c0-0.381-0.309-0.689-0.689-0.689H9.568
                                                    c-0.005-0.97-0.794-1.756-1.766-1.756s-1.76,0.786-1.766,1.756H5.307c-0.38,0-0.688,0.309-0.688,0.689v2.885
                                                    C4.618,5.797,4.926,6.105,5.307,6.105z M7.802,1.063c0.432,0,0.782,0.348,0.788,0.778H7.014C7.019,1.411,7.37,1.063,7.802,1.063z"
                                                    />
                                                <path fill="#64BD61" d="M21.858,4.73c-0.023-0.128-0.096-0.24-0.203-0.315L20.4,3.54c-0.085-0.06-0.184-0.088-0.279-0.088
                                                    c-0.152,0-0.307,0.072-0.399,0.208l-8.898,12.759l2.056,1.435l8.897-12.759C21.852,4.988,21.881,4.857,21.858,4.73z"/>
                                                <path fill="#64BD61" d="M9.422,18.503l0.128,1.498c0.006,0.087,0.053,0.163,0.122,0.214c0.05,0.034,0.108,0.054,0.167,0.054
                                                    c0.025,0,0.051-0.004,0.075-0.012l1.451-0.397c0.066-0.018,0.123-0.059,0.163-0.113l0.544-0.78l-2.057-1.436l-0.544,0.782
                                                    C9.433,18.367,9.415,18.435,9.422,18.503z"/>
                                            </g>
                                        </g>
                                        </svg>
                                </span>
                            </div>
                            <div class="info-text-right">
                                <span><?= $block->escapeHtml(__('Enjoy exclusive offers and superior discounts when you shop with us')) ?></span>
                            </div>
                        </div>
                        <div class="primary">
                                <a href="<?php echo $url."customer/account/create"; ?>" class="action create primary"><span><?= $block->escapeHtml(__('Register')) ?></span>
                                </a>
                            </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">
require(['jquery','mage/validation'], function($){
    var dataForm = $('#login-form-popup');
    dataForm.mage('validation', {});
    $('button#submit-button').click( function() { //can be replaced with any event
        var status = dataForm.validation('isValid'); //validates form and returns boolean
        if(status){ //form is valid

	        jQuery('li.logout-popup').addClass('login_error_focus');
			var customloginpopupurl = "<?php echo $this->getBaseUrl().'homebanner/index/loginpopuppost';?>";
			var email = jQuery('#emailnew').val();
			var passwordnew = jQuery('#passwordnew').val();
			var param = {'email': email, 'password': passwordnew};
			jQuery('#popup_login_error_msg').hide();
			jQuery('#popup_login_error_msg').html('');
			jQuery.ajax({
                showLoader: true,
                url: customloginpopupurl,
                data: param,
                type: "POST",
                dataType: 'json'
            }).done(function (response) {
                if (response.errors) {
                    jQuery('#popup_login_error_msg').show();
                    jQuery('#popup_login_error_msg').html(response.message);
                    jQuery('li.logout-popup').addClass('login_error_focus');
                    return false;
                }
                else {
                    jQuery('li.logout-popup').removeClass('login_error_focus');
                    location.reload();
                }
            });

		    return false;
        }
    });
});
</script>
