<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php 
	$object = \Magento\Framework\App\ObjectManager::getInstance();
    $IsHome = $object->get('\Magento\Theme\Block\Html\Header\Logo')->isHomePage();
?>

<div class="copyright">
    <div id="back-top" class="scrollToTop"><div class="back-inner"><svg x="0px" y="0px" width="17.583px" height="25px" viewBox="0 0 17.583 25">
<path fill="#FFFFFF" d="M17.318,8.159c0.354,0.353,0.354,0.908,0,1.261c-0.34,0.34-0.908,0.34-1.248,0L9.68,3.029v21.09
	c0,0.49-0.39,0.882-0.882,0.882s-0.895-0.392-0.895-0.882V3.028L1.525,9.419c-0.353,0.341-0.92,0.341-1.26,0
	c-0.353-0.353-0.353-0.908,0-1.26l7.904-7.904c0.341-0.341,0.908-0.341,1.248,0L17.318,8.159z"/>
</svg></div></div> 
    <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
    <span class="signature"><a href="http://www.23digital.com.au/web-design/" title="Website Design" target="_blank"><?php echo __('Website Design '); ?></a><?php echo __('by  '); ?><a href="http://www.23digital.com.au/" target="_blank" title="Digital Agencies"> <?php echo __('23 Digital'); ?></a></span>
</div>

