<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?= /* @escapeNotVerified */ __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?= /* @escapeNotVerified */ __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?= /* @escapeNotVerified */ __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?= /* @escapeNotVerified */ __('Page') ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage()): ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?= /* @escapeNotVerified */ $text ? 'link ' : 'action ' ?> previous" href="<?= /* @escapeNotVerified */ $block->getPreviousPageUrl() ?>" title="<?= /* @escapeNotVerified */ $text ? $text : __('Previous') ?>">
                        <span class="label"><?= /* @escapeNotVerified */ __('Page') ?></span>
                        <span><?= /* @escapeNotVerified */ $text ? $text : __('Previous') ?></span>
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             width="18px" height="13px" viewBox="0 0 18 13" enable-background="new 0 0 18 13" xml:space="preserve">
                        <path fill="#606B72" d="M5.839,12.475c0.237,0.246,0.637,0.246,0.883,0c0.239-0.239,0.239-0.636,0-0.874L2.246,7.123h15.02
                            c0.344,0,0.617-0.275,0.617-0.619s-0.273-0.626-0.617-0.626H2.245l4.476-4.469c0.239-0.246,0.239-0.645,0-0.883
                            c-0.246-0.246-0.645-0.246-0.882,0L0.303,6.063c-0.248,0.238-0.248,0.637,0,0.873L5.839,12.475z"/>
                        </svg>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?= /* @escapeNotVerified */ $block->getFirstPageUrl() ?>">
                        <span class="label"><?= /* @escapeNotVerified */ __('Page') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?= /* @escapeNotVerified */ $block->getPreviousJumpUrl() ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)): ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?= /* @escapeNotVerified */ __('You\'re currently reading page') ?></span>
                            <span><?= /* @escapeNotVerified */ $_page ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?= /* @escapeNotVerified */ $block->getPageUrl($_page) ?>" class="page">
                            <span class="label"><?= /* @escapeNotVerified */ __('Page') ?></span>
                            <span><?= /* @escapeNotVerified */ $_page ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?= /* @escapeNotVerified */ $block->getNextJumpUrl() ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
              <li class="item">
                  <a class="page last" href="<?= /* @escapeNotVerified */ $block->getLastPageUrl() ?>">
                      <span class="label"><?= /* @escapeNotVerified */ __('Page') ?></span>
                      <span><?= /* @escapeNotVerified */ $block->getLastPageNum() ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()): ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?= /* @escapeNotVerified */ $text ? 'link ' : 'action ' ?> next" href="<?= /* @escapeNotVerified */ $block->getNextPageUrl() ?>" title="<?= /* @escapeNotVerified */ $text ? $text : __('Next') ?>">
                        <span class="label"><?= /* @escapeNotVerified */ __('Page') ?></span>
                        <span><?= /* @escapeNotVerified */ $text ? $text : __('Next') ?></span>
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             width="18px" height="13px" viewBox="0 0 18 13" enable-background="new 0 0 18 13" xml:space="preserve">
                        <path fill="#606B72" d="M12.161,0.526c-0.237-0.247-0.637-0.247-0.883,0c-0.239,0.239-0.239,0.636,0,0.874l4.476,4.478H0.735
                            c-0.345,0-0.618,0.275-0.618,0.619S0.39,7.123,0.735,7.123h15.02l-4.476,4.469c-0.239,0.246-0.239,0.645,0,0.883
                            c0.246,0.246,0.645,0.246,0.882,0l5.536-5.537c0.248-0.238,0.248-0.637,0-0.873L12.161,0.526z"/>
                        </svg>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter">
            <strong class="limiter-label"><?= /* @escapeNotVerified */ __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?= /* @escapeNotVerified */ $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?= /* @escapeNotVerified */ $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?= /* @escapeNotVerified */ __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
