<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
if(count($this->getHomepageNewReleasesProductCollection()) > 0){?>
<div class="container">
    <div class="section-title-sec">
        <h2 class="section-title"><?php echo __("New Releases"); ?></h2>
	       <p class="section-text"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_newreleases_products_text')->toHtml(); ?></p>
    </div>

	<div class="dcs-popular-main">
		<div class="owl-dcs-product-list owl-carousel1 cf">
			<?php foreach ($this->getHomepageNewReleasesProductCollection()  as $k => $_product) { ?>
				<div class="item product-item">
					<div class="pro-inner">
                        <div class="product-item-img">
					       <a href="<?php echo $_product->getProductUrl(); ?>">
							   
							   <?php 	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
										$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
										$imagewidth=268;
                                		$imageheight=268;
                                		$image_url = $imageHelper->init($_product, 'category_page_grid')->setImageFile($_product->getFile())->resize($imagewidth, $imageheight)->getUrl(); 
										
										//$imageBlock = $this->getImage($_product,'category_page_grid');
										//echo $imageBlock->toHtml();														  
								?>
							   <img class="product-image-photo owl-lazy" src="<?php echo $image_url; ?>" width="268" height="268" alt="<?php echo $_product->getName(); ?>" />                               
					       </a>
                        </div>
					<div class="product-info">
						<div class="product-name">
								<a class="product-item-link" href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $_product->getName(); ?>"><?php echo $_product->getName(); ?></a>
                        </div>
												
								<div class="price-box">
									<?php echo $this->getProductPrice($_product); ?> 
								</div>
							
								<div class="btn-prod-cart">
								<a class="product-item-link" title="<?=  __('Add to Cart') ?>" href="<?= $_product->getProductUrl() ?>">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="24px" height="19.381px" viewBox="0 0 24 19.381" enable-background="new 0 0 24 19.381" xml:space="preserve">
                                <g>
                                    <path fill="#FFFFFF" d="M21.029,12.655l2.828-8.464c0.142-0.407,0.035-0.652-0.08-0.813c-0.293-0.413-0.896-0.417-1.012-0.417
                                        L6.78,2.957L6.353,0.933C6.237,0.456,5.897,0,5.211,0H0.719C0.253,0,0,0.218,0,0.654v1.168c0,0.421,0.253,0.531,0.735,0.531h3.793
                                        l2.903,12.323c-0.461,0.49-0.712,1.2-0.712,1.866c0,1.461,1.164,2.809,2.65,2.809c1.403,0,2.456-1.315,2.627-2.099h5.653
                                        c0.172,0.783,1.024,2.129,2.627,2.129c1.461,0,2.649-1.266,2.649-2.724c0-1.453-0.884-2.738-2.634-2.738
                                        c-0.73,0-1.593,0.394-1.995,0.979h-6.946c-0.504-0.781-1.193-1.025-1.889-1.054l-0.097-0.515h10.571
                                        C20.73,13.329,20.887,13.041,21.029,12.655z M20.296,15.628c0.551,0,0.996,0.447,0.996,0.996s-0.445,0.995-0.996,0.995
                                        s-0.997-0.443-0.997-0.995C19.3,16.075,19.745,15.628,20.296,15.628z M10.354,16.624c0,0.558-0.452,1.01-1.006,1.01
                                        c-0.556-0.003-1.008-0.452-1.008-1.01c0-0.555,0.452-1.007,1.008-1.007C9.903,15.617,10.354,16.069,10.354,16.624z"/>
                                </g>
                                </svg>
                                    </a>
								</div>
													
								<?php /*if ($_product->isSaleable()){ ?>
								<?php 	$addToCartUrl = $this->getAddToCartUrl($_product);  ?>
								<div class="cart-icon">
								<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
									<?php echo $block->getBlockHtml('formkey')?>									
									<button type="submit" title="<?php echo __("Add to Cart"); ?>" class="action tocart primary"><span><?php echo __("Add to Cart"); ?></span></button>
								</form>
								</div>
								
							<?php }*/ ?>
							
						</div>
						</div>
				</div>
			<?php } ?>
		</div>
		
	</div>
</div>
<?php } ?>