<script type="text/javascript">
	 require([
            'jquery',
        ], function ($) {
            $(document).ready(function () {
				setTimeout(function(){  
					var imgsrc='<?php echo $this->getViewFileUrl('Dcs_Downloadcatalogue::images/file.png'); ?>';
					jQuery(".downloadcatalogue-index-edit #downloadcatalogue_main_catalogue_file_image").attr("src",imgsrc);					
				}, 1000);

			});
		 });
	 </script>