<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit $block */

/** @var \Magento\Wishlist\Model\Item $item */
/*$item = $block->getItem();
$product = $item->getProduct();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$sql = "SELECT parent_id FROM `catalog_product_relation` where `child_id` =".$product->getId();
$result = $connection->fetchAll($sql);
if(isset($result[0]['parent_id']) && (int)$result[0]['parent_id'] > 0 )
		{
			 $parentProduct = $objectManager->create('Magento\Catalog\Model\Product')->load($result[0]['parent_id']);
			$parentUrl	   = $parentProduct->getUrlModel()->getUrl($parentProduct);
		}
else
{
		$parentUrl	   = $block->escapeUrl($block->getItemConfigureUrl($item));
}

?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a title="<?php echo __('Edit Item') ?>" class="action edit button-small" href="<?= $parentUrl  ?>">
        <span><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span>
    </a>
<?php endif */ ?>
